name: cheesecutter # you probably want to 'snapcraft register <name>'
version: '2.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: CheeseCutter SID music editor
description:
  CheeseCutter is a tracker program for composing music for the SID chip.
  It uses the reSID engine for SID emulation. Packed files can be played
  on a real C64.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  ccutter:
    command: ccutter
    environment:
      CC_HOME: $SNAP_USER_COMMON
    plugs:
      - x11
      - pulseaudio
      - home

  ct2util:
    command: ct2util
    plugs:
      - home

parts:
  ccutter:
    plugin: make
    stage-packages:
      - libsdl1.2debian
    build-packages:
      - ldc
    source: ../
